using DWIS.API.DTO;
using DWIS.RigOS.Common.Worker;
using DWIS.Vocabulary.Schemas;
using OSDC.DotnetLibraries.Drilling.DrillingProperties;
using OSDC.UnitConversion.Conversion;
using OSDC.UnitConversion.Conversion.DrillingEngineering;
using System.Reflection;

namespace DWIS.DAQBridge.BaseStar.Model
{
    public class MechanicalSubOutputDataMudPulseTelemetry : DWISDataWithOPCUA
    {
        private static readonly Lazy<IReadOnlyDictionary<PropertyInfo, OPCUANode>> LocalOPCUANodes = new(BuildOPCUANodes(typeof(MechanicalSubOutputDataMudPulseTelemetry)));
        private static readonly Lazy<IReadOnlyDictionary<PropertyInfo, Dictionary<string, QuerySpecification>>> LocalSparQLQueries = new(BuildSparQLQueries(typeof(MechanicalSubOutputDataMudPulseTelemetry)));
        private static readonly Lazy<IReadOnlyDictionary<PropertyInfo, ManifestFile>> LocalManifests = new(BuildManifests(typeof(MechanicalSubOutputDataMudPulseTelemetry), "BaseStarDataManifest", "Halliburton", "DWISBridge"));
        public override Lazy<IReadOnlyDictionary<PropertyInfo, OPCUANode>> OPCUANodes { get => LocalOPCUANodes; }
        public override Lazy<IReadOnlyDictionary<PropertyInfo, Dictionary<string, QuerySpecification>>> SparQLQueries { get => LocalSparQLQueries; }
        public override Lazy<IReadOnlyDictionary<PropertyInfo, ManifestFile>> Manifests { get => LocalManifests; }

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("BaseStarAverageRotationalSpeed")]
        [SemanticFact("BaseStarAverageRotationalSpeed", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaseStarAverageRotationalSpeed#01", Nouns.Enum.DerivedMeasurement)]
        [SemanticFact("BaseStarAverageRotationalSpeed#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaseStarAverageRotationalSpeed#01", Verbs.Enum.HasDynamicValue, "BaseStarAverageRotationalSpeed")]
        [SemanticFact("BaseStarAverageRotationalSpeed#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.AngularVelocityDrilling)]
        [SemanticFact("MovingAverageBaseStarAverageRotationalSpeed", Nouns.Enum.MovingAverage)]
        [SemanticFact("BaseStarAverageRotationalSpeed#01", Verbs.Enum.IsTransformationOutput, "MovingAverageBaseStarAverageRotationalSpeed")]
        [SemanticFact("BaseStarRotationalSpeed", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaseStarRotationalSpeed#01", Nouns.Enum.DirectMeasurement)]
        [SemanticFact("BaseStarRotationalSpeed#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaseStarRotationalSpeed#01", Verbs.Enum.HasDynamicValue, "BaseStarRotationalSpeed")]
        [SemanticFact("BaseStarRotationalSpeed#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.AngularVelocityDrilling)]
        [SemanticFact("BaseStarRotationalSpeed#01", Verbs.Enum.IsTransformationInput, "MovingAverageBaseStarAverageRotationalSpeed")]
        [SemanticFact("GaussianUncertaintyBaseStarAverageRotationalSpeed#01", Nouns.Enum.GaussianUncertainty)]
        [SemanticFact("BaseStarAverageRotationalSpeed#01", Verbs.Enum.HasUncertainty, "GaussianUncertaintyBaseStarAverageRotationalSpeed#01")]
        [SemanticFact("GaussianUncertaintyBaseStarAverageRotationalSpeed#01", Verbs.Enum.HasUncertaintyMean, "BaseStarAverageRotationalSpeed#01")]
        [SemanticFact("mudPulseTelemetry", Nouns.Enum.MudPulseTelemetry)]
        [SemanticFact("BaseStarAverageRotationalSpeed#01", Verbs.Enum.IsTransmittedBy, "mudPulseTelemetry")]
        [SemanticFact("BHA#01", Nouns.Enum.BHAMechanicalLogicalElement)]
        [SemanticFact("BaseStarAverageRotationalSpeed#01", Verbs.Enum.IsMechanicallyLocatedAt, "BHA#01")]
        [SemanticFact("BaseStarRotationalSpeed#01", Verbs.Enum.IsMechanicallyLocatedAt, "BHA#01")]
        [SemanticFact("Halliburton#01", Nouns.Enum.InstrumentationCompany)]
        [SemanticFact("BaseStarAverageRotationalSpeed#01", Verbs.Enum.IsProvidedBy, "Halliburton#01")]
        [SemanticFact("BaseStarRotationalSpeed#01", Verbs.Enum.IsProvidedBy, "Halliburton#01")]
        [OPCUANode("http://ddhub.no/BaseStarDataManifest/Variables/", "BaseStarDataManifest.", "AverageRotationalSpeed")]
        public ScalarProperty? AverageRotationalSpeed { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("BaseStarPeakRotationalSpeed")]
        [SemanticFact("BaseStarPeakRotationalSpeed", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaseStarPeakRotationalSpeed#01", Nouns.Enum.DerivedMeasurement)]
        [SemanticFact("BaseStarPeakRotationalSpeed#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaseStarPeakRotationalSpeed#01", Verbs.Enum.HasDynamicValue, "BaseStarPeakRotationalSpeed")]
        [SemanticFact("BaseStarPeakRotationalSpeed#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.AngularVelocityDrilling)]
        [SemanticFact("MovingMaxBaseStarPeakRotationalSpeed", Nouns.Enum.MovingMax)]
        [SemanticFact("BaseStarPeakRotationalSpeed#01", Verbs.Enum.IsTransformationOutput, "MovingMaxBaseStarPeakRotationalSpeed")]
        [SemanticFact("BaseStarRotationalSpeed", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaseStarRotationalSpeed#01", Nouns.Enum.DerivedMeasurement)]
        [SemanticFact("BaseStarRotationalSpeed#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaseStarRotationalSpeed#01", Verbs.Enum.HasDynamicValue, "BaseStarRotationalSpeed")]
        [SemanticFact("BaseStarRotationalSpeed#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.AngularVelocityDrilling)]
        [SemanticFact("BaseStarRotationalSpeed#01", Verbs.Enum.IsTransformationInput, "MovingMaxBaseStarPeakRotationalSpeed")]
        [SemanticFact("GaussianUncertaintyBaseStarPeakRotationalSpeed#01", Nouns.Enum.GaussianUncertainty)]
        [SemanticFact("BaseStarPeakRotationalSpeed#01", Verbs.Enum.HasUncertainty, "GaussianUncertaintyBaseStarPeakRotationalSpeed#01")]
        [SemanticFact("GaussianUncertaintyBaseStarPeakRotationalSpeed#01", Verbs.Enum.HasUncertaintyMean, "BaseStarPeakRotationalSpeed#01")]
        [SemanticFact("mudPulseTelemetry", Nouns.Enum.MudPulseTelemetry)]
        [SemanticFact("BaseStarPeakRotationalSpeed#01", Verbs.Enum.IsTransmittedBy, "mudPulseTelemetry")]
        [SemanticFact("BHA#01", Nouns.Enum.BHAMechanicalLogicalElement)]
        [SemanticFact("BaseStarPeakRotationalSpeed#01", Verbs.Enum.IsMechanicallyLocatedAt, "BHA#01")]
        [SemanticFact("BaseStarRotationalSpeed#01", Verbs.Enum.IsMechanicallyLocatedAt, "BHA#01")]
        [SemanticFact("Halliburton#01", Nouns.Enum.InstrumentationCompany)]
        [SemanticFact("BaseStarPeakRotationalSpeed#01", Verbs.Enum.IsProvidedBy, "Halliburton#01")]
        [SemanticFact("BaseStarRotationalSpeed#01", Verbs.Enum.IsProvidedBy, "Halliburton#01")]
        [OPCUANode("http://ddhub.no/BaseStarDataManifest/Variables/", "BaseStarDataManifest.", "MaxRotationalSpeed")]
        public ScalarProperty? MaxRotationalSpeed { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("BaseStarStickSlipIndicator")]
        [SemanticFact("BaseStarStickSlipIndicator", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaseStarStickSlipIndicator#01", Nouns.Enum.ComputedData)]
        [SemanticFact("BaseStarStickSlipIndicator#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaseStarStickSlipIndicator#01", Verbs.Enum.HasDynamicValue, "BaseStarStickSlipIndicator")]
        [SemanticFact("BaseStarStickSlipIndicator#01", Verbs.Enum.IsOfMeasurableQuantity, BasePhysicalQuantity.QuantityEnum.DimensionLessStandard)]
        [SemanticFact("StickSlipIndicatorComputation", Nouns.Enum.Estimator)]
        [SemanticFact("BaseStarStickSlipIndicator#01", Verbs.Enum.IsTransformationOutput, "StickSlipIndicatorComputation")]
        [SemanticFact("BaseStarRotationalSpeed", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaseStarRotationalSpeed#01", Nouns.Enum.DerivedMeasurement)]
        [SemanticFact("BaseStarRotationalSpeed#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaseStarRotationalSpeed#01", Verbs.Enum.HasDynamicValue, "BaseStarRotationalSpeed")]
        [SemanticFact("BaseStarRotationalSpeed#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.AngularVelocityDrilling)]
        [SemanticFact("BaseStarRotationalSpeed#01", Verbs.Enum.IsTransformationInput, "StickSlipIndicatorComputation")]
        [SemanticFact("GaussianUncertaintyBaseStarStickSlipIndicator#01", Nouns.Enum.GaussianUncertainty)]
        [SemanticFact("BaseStarStickSlipIndicator#01", Verbs.Enum.HasUncertainty, "GaussianUncertaintyBaseStarStickSlipIndicator#01")]
        [SemanticFact("GaussianUncertaintyBaseStarStickSlipIndicator#01", Verbs.Enum.HasUncertaintyMean, "BaseStarStickSlipIndicator#01")]
        [SemanticFact("mudPulseTelemetry", Nouns.Enum.MudPulseTelemetry)]
        [SemanticFact("BaseStarStickSlipIndicator#01", Verbs.Enum.IsTransmittedBy, "mudPulseTelemetry")]
        [SemanticFact("stickSlipIncident", Nouns.Enum.StickSlip)]
        [SemanticFact("BaseStarStickSlipIndicator#01", Verbs.Enum.IsRelatedToDrillingIncident, "stickSlipIncident")]
        [SemanticFact("BHA#01", Nouns.Enum.BHAMechanicalLogicalElement)]
        [SemanticFact("BaseStarStickSlipIndicator#01", Verbs.Enum.IsMechanicallyLocatedAt, "BHA#01")]
        [SemanticFact("BaseStarRotationalSpeed#01", Verbs.Enum.IsMechanicallyLocatedAt, "BHA#01")]
        [SemanticFact("Halliburton#01", Nouns.Enum.InstrumentationCompany)]
        [SemanticFact("BaseStarStickSlipIndicator#01", Verbs.Enum.IsProvidedBy, "Halliburton#01")]
        [SemanticFact("BaseStarRotationalSpeed#01", Verbs.Enum.IsProvidedBy, "Halliburton#01")]
        [OPCUANode("http://ddhub.no/BaseStarDataManifest/Variables/", "BaseStarDataManifest.", "StickSlipIndicator")]
        public ScalarProperty? StickSlipIndicator { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("BaseStarMeasuredPeakRadialAcceleration")]
        [SemanticFact("BaseStarMeasuredPeakRadialAcceleration", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaseStarMeasuredPeakRadialAcceleration#01", Nouns.Enum.DerivedMeasurement)]
        [SemanticFact("BaseStarMeasuredPeakRadialAcceleration#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaseStarMeasuredPeakRadialAcceleration#01", Verbs.Enum.HasDynamicValue, "BaseStarMeasuredPeakRadialAcceleration")]
        [SemanticFact("BaseStarMeasuredPeakRadialAcceleration#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.AccelerationDrilling)]
        [SemanticFact("MovingMaxBaseStarMeasuredPeakRadialAcceleration", Nouns.Enum.MovingMax)]
        [SemanticFact("BaseStarMeasuredPeakRadialAcceleration#01", Verbs.Enum.IsTransformationOutput, "MovingMaxBaseStarMeasuredPeakRadialAcceleration")]
        [SemanticFact("BaseStarMeasuredRadialAcceleration", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaseStarMeasuredRadialAcceleration#01", Nouns.Enum.DerivedMeasurement)]
        [SemanticFact("BaseStarMeasuredRadialAcceleration#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaseStarMeasuredRadialAcceleration#01", Verbs.Enum.HasDynamicValue, "BaseStarMeasuredRadialAcceleration")]
        [SemanticFact("BaseStarMeasuredRadialAcceleration#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.AccelerationDrilling)]
        [SemanticFact("BaseStarMeasuredRadialAcceleration#01", Verbs.Enum.IsTransformationInput, "MovingMaxBaseStarMeasuredPeakRadialAcceleration")]
        [SemanticFact("GaussianUncertaintyBaseStarMeasuredPeakRadialAcceleration#01", Nouns.Enum.GaussianUncertainty)]
        [SemanticFact("BaseStarMeasuredPeakRadialAcceleration#01", Verbs.Enum.HasUncertainty, "GaussianUncertaintyBaseStarMeasuredPeakRadialAcceleration#01")]
        [SemanticFact("GaussianUncertaintyBaseStarMeasuredPeakRadialAcceleration#01", Verbs.Enum.HasUncertaintyMean, "BaseStarMeasuredPeakRadialAcceleration#01")]
        [SemanticFact("mudPulseTelemetry", Nouns.Enum.MudPulseTelemetry)]
        [SemanticFact("BaseStarMeasuredPeakRadialAcceleration#01", Verbs.Enum.IsTransmittedBy, "mudPulseTelemetry")]
        [SemanticFact("pipeSection#01", Nouns.Enum.PipeSectionMechanicalLogicalElement)]
        [SemanticFact("BaseStarMeasuredPeakRadialAcceleration#01", Verbs.Enum.IsMechanicallyLocatedAt, "pipeSection#01")]
        [SemanticFact("BaseStarMeasuredRadialAcceleration#01", Verbs.Enum.IsMechanicallyLocatedAt, "pipeSection#01")]
        [SemanticFact("RadialReferenceFrame#01", Nouns.Enum.RadialReferenceFrame)]
        [SemanticFact("BaseStarMeasuredPeakRadialAcceleration#01", Verbs.Enum.HasReferenceFrame, "RadialReferenceFrame#01")]
        [SemanticFact("BaseStarMeasuredRadialAcceleration#01", Verbs.Enum.HasReferenceFrame, "RadialReferenceFrame#01")]
        [SemanticFact("Halliburton#01", Nouns.Enum.InstrumentationCompany)]
        [SemanticFact("BaseStarMeasuredPeakRadialAcceleration#01", Verbs.Enum.IsProvidedBy, "Halliburton#01")]
        [SemanticFact("BaseStarMeasuredRadialAcceleration#01", Verbs.Enum.IsProvidedBy, "Halliburton#01")]
        [OPCUANode("http://ddhub.no/BaseStarDataManifest/Variables/", "BaseStarDataManifest.", "PeakRadialAcceleration")]
        public ScalarProperty? PeakRadialAcceleration { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("BaseStarMeasuredAverageRadialAcceleration")]
        [SemanticFact("BaseStarMeasuredAverageRadialAcceleration", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaseStarMeasuredAverageRadialAcceleration#01", Nouns.Enum.DerivedMeasurement)]
        [SemanticFact("BaseStarMeasuredAverageRadialAcceleration#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaseStarMeasuredAverageRadialAcceleration#01", Verbs.Enum.HasDynamicValue, "BaseStarMeasuredAverageRadialAcceleration")]
        [SemanticFact("BaseStarMeasuredAverageRadialAcceleration#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.AccelerationDrilling)]
        [SemanticFact("MovingAverageBaseStarMeasuredAverageRadialAcceleration", Nouns.Enum.MovingAverage)]
        [SemanticFact("BaseStarMeasuredAverageRadialAcceleration#01", Verbs.Enum.IsTransformationOutput, "MovingAverageBaseStarMeasuredAverageRadialAcceleration")]
        [SemanticFact("BaseStarMeasuredRadialAcceleration", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaseStarMeasuredRadialAcceleration#01", Nouns.Enum.DerivedMeasurement)]
        [SemanticFact("BaseStarMeasuredRadialAcceleration#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaseStarMeasuredRadialAcceleration#01", Verbs.Enum.HasDynamicValue, "BaseStarMeasuredRadialAcceleration")]
        [SemanticFact("BaseStarMeasuredRadialAcceleration#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.AccelerationDrilling)]
        [SemanticFact("BaseStarMeasuredRadialAcceleration#01", Verbs.Enum.IsTransformationInput, "MovingAverageBaseStarMeasuredAverageRadialAcceleration")]
        [SemanticFact("GaussianUncertaintyBaseStarMeasuredAverageRadialAcceleration#01", Nouns.Enum.GaussianUncertainty)]
        [SemanticFact("BaseStarMeasuredAverageRadialAcceleration#01", Verbs.Enum.HasUncertainty, "GaussianUncertaintyBaseStarMeasuredAverageRadialAcceleration#01")]
        [SemanticFact("GaussianUncertaintyBaseStarMeasuredAverageRadialAcceleration#01", Verbs.Enum.HasUncertaintyMean, "BaseStarMeasuredAverageRadialAcceleration#01")]
        [SemanticFact("mudPulseTelemetry", Nouns.Enum.MudPulseTelemetry)]
        [SemanticFact("BaseStarMeasuredAverageRadialAcceleration#01", Verbs.Enum.IsTransmittedBy, "mudPulseTelemetry")]
        [SemanticFact("pipeSection#01", Nouns.Enum.PipeSectionMechanicalLogicalElement)]
        [SemanticFact("BaseStarMeasuredAverageRadialAcceleration#01", Verbs.Enum.IsMechanicallyLocatedAt, "pipeSection#01")]
        [SemanticFact("BaseStarMeasuredRadialAcceleration#01", Verbs.Enum.IsMechanicallyLocatedAt, "pipeSection#01")]
        [SemanticFact("RadialReferenceFrame#01", Nouns.Enum.RadialReferenceFrame)]
        [SemanticFact("BaseStarMeasuredAverageRadialAcceleration#01", Verbs.Enum.HasReferenceFrame, "RadialReferenceFrame#01")]
        [SemanticFact("BaseStarMeasuredRadialAcceleration#01", Verbs.Enum.HasReferenceFrame, "RadialReferenceFrame#01")]
        [SemanticFact("Halliburton#01", Nouns.Enum.InstrumentationCompany)]
        [SemanticFact("BaseStarMeasuredAverageRadialAcceleration#01", Verbs.Enum.IsProvidedBy, "Halliburton#01")]
        [SemanticFact("BaseStarMeasuredRadialAcceleration#01", Verbs.Enum.IsProvidedBy, "Halliburton#01")]
        [OPCUANode("http://ddhub.no/BaseStarDataManifest/Variables/", "BaseStarDataManifest.", "AverageRadialAcceleration")]
        public ScalarProperty? AverageRadialAcceleration { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("BaseStarMeasuredPeakAxialAcceleration")]
        [SemanticFact("BaseStarMeasuredPeakAxialAcceleration", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaseStarMeasuredPeakAxialAcceleration#01", Nouns.Enum.DerivedMeasurement)]
        [SemanticFact("BaseStarMeasuredPeakAxialAcceleration#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaseStarMeasuredPeakAxialAcceleration#01", Verbs.Enum.HasDynamicValue, "BaseStarMeasuredPeakAxialAcceleration")]
        [SemanticFact("BaseStarMeasuredPeakAxialAcceleration#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.AccelerationDrilling)]
        [SemanticFact("MovingMaxBaseStarMeasuredPeakAxialAcceleration", Nouns.Enum.MovingMax)]
        [SemanticFact("BaseStarMeasuredPeakAxialAcceleration#01", Verbs.Enum.IsTransformationOutput, "MovingMaxBaseStarMeasuredPeakAxialAcceleration")]
        [SemanticFact("BaseStarMeasuredAxialAcceleration", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaseStarMeasuredAxialAcceleration#01", Nouns.Enum.DerivedMeasurement)]
        [SemanticFact("BaseStarMeasuredAxialAcceleration#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaseStarMeasuredAxialAcceleration#01", Verbs.Enum.HasDynamicValue, "BaseStarMeasuredAxialAcceleration")]
        [SemanticFact("BaseStarMeasuredAxialAcceleration#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.AccelerationDrilling)]
        [SemanticFact("BaseStarMeasuredAxialAcceleration#01", Verbs.Enum.IsTransformationInput, "MovingMaxBaseStarMeasuredPeakAxialAcceleration")]
        [SemanticFact("GaussianUncertaintyBaseStarMeasuredPeakAxialAcceleration#01", Nouns.Enum.GaussianUncertainty)]
        [SemanticFact("BaseStarMeasuredPeakAxialAcceleration#01", Verbs.Enum.HasUncertainty, "GaussianUncertaintyBaseStarMeasuredPeakAxialAcceleration#01")]
        [SemanticFact("GaussianUncertaintyBaseStarMeasuredPeakAxialAcceleration#01", Verbs.Enum.HasUncertaintyMean, "BaseStarMeasuredPeakAxialAcceleration#01")]
        [SemanticFact("mudPulseTelemetry", Nouns.Enum.MudPulseTelemetry)]
        [SemanticFact("BaseStarMeasuredPeakAxialAcceleration#01", Verbs.Enum.IsTransmittedBy, "mudPulseTelemetry")]
        [SemanticFact("BHA#01", Nouns.Enum.BHAMechanicalLogicalElement)]
        [SemanticFact("BaseStarMeasuredPeakAxialAcceleration#01", Verbs.Enum.IsMechanicallyLocatedAt, "BHA#01")]
        [SemanticFact("BaseStarMeasuredAxialAcceleration#01", Verbs.Enum.IsMechanicallyLocatedAt, "BHA#01")]
        [SemanticFact("AxialReferenceFrame#01", Nouns.Enum.AxialReferenceFrame)]
        [SemanticFact("BaseStarMeasuredPeakAxialAcceleration#01", Verbs.Enum.HasReferenceFrame, "AxialReferenceFrame#01")]
        [SemanticFact("BaseStarMeasuredAxialAcceleration#01", Verbs.Enum.HasReferenceFrame, "AxialReferenceFrame#01")]
        [SemanticFact("Halliburton#01", Nouns.Enum.InstrumentationCompany)]
        [SemanticFact("BaseStarMeasuredPeakAxialAcceleration#01", Verbs.Enum.IsProvidedBy, "Halliburton#01")]
        [SemanticFact("BaseStarMeasuredAxialAcceleration#01", Verbs.Enum.IsProvidedBy, "Halliburton#01")]
        [OPCUANode("http://ddhub.no/BaseStarDataManifest/Variables/", "BaseStarDataManifest.", "PeakAxialAcceleration")]
        public ScalarProperty? PeakAxialAcceleration { get; set; } = null;

        // ------------------------
        // RAW WOB + TARE + BIT WOB
        // ------------------------

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("BaseStarMeasuredAverageRawWeight")]
        [SemanticFact("BaseStarMeasuredAverageRawWeight", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaseStarMeasuredAverageRawWeight#01", Nouns.Enum.DerivedMeasurement)]
        [SemanticFact("BaseStarMeasuredAverageRawWeight#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaseStarMeasuredAverageRawWeight#01", Verbs.Enum.HasDynamicValue, "BaseStarMeasuredAverageRawWeight")]
        [SemanticFact("BaseStarMeasuredAverageRawWeight#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.WeightOnBitDrilling)]
        [SemanticFact("MovingAverageBaseStarMeasuredAverageRawWeight", Nouns.Enum.MovingAverage)]
        [SemanticFact("BaseStarMeasuredAverageRawWeight#01", Verbs.Enum.IsTransformationOutput, "MovingAverageBaseStarMeasuredAverageRawWeight")]
        [SemanticFact("BaseStarMeasuredRawWeight", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaseStarMeasuredRawWeight#01", Nouns.Enum.DerivedMeasurement)]
        [SemanticFact("BaseStarMeasuredRawWeight#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaseStarMeasuredRawWeight#01", Verbs.Enum.HasDynamicValue, "BaseStarMeasuredRawWeight")]
        [SemanticFact("BaseStarMeasuredRawWeight#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.WeightOnBitDrilling)]
        [SemanticFact("BaseStarMeasuredRawWeight#01", Verbs.Enum.IsTransformationInput, "MovingAverageBaseStarMeasuredAverageRawWeight")]
        [SemanticFact("GaussianUncertaintyBaseStarMeasuredAverageRawWeight#01", Nouns.Enum.GaussianUncertainty)]
        [SemanticFact("BaseStarMeasuredAverageRawWeight#01", Verbs.Enum.HasUncertainty, "GaussianUncertaintyBaseStarMeasuredAverageRawWeight#01")]
        [SemanticFact("GaussianUncertaintyBaseStarMeasuredAverageRawWeight#01", Verbs.Enum.HasUncertaintyMean, "BaseStarMeasuredAverageRawWeight#01")]
        [SemanticFact("mudPulseTelemetry", Nouns.Enum.MudPulseTelemetry)]
        [SemanticFact("BaseStarMeasuredAverageRawWeight#01", Verbs.Enum.IsTransmittedBy, "mudPulseTelemetry")]
        [SemanticFact("BHA#01", Nouns.Enum.BHAMechanicalLogicalElement)]
        [SemanticFact("BaseStarMeasuredAverageRawWeight#01", Verbs.Enum.IsMechanicallyLocatedAt, "BHA#01")]
        [SemanticFact("BaseStarMeasuredRawWeight#01", Verbs.Enum.IsMechanicallyLocatedAt, "BHA#01")]
        [SemanticFact("Halliburton#01", Nouns.Enum.InstrumentationCompany)]
        [SemanticFact("BaseStarMeasuredAverageRawWeight#01", Verbs.Enum.IsProvidedBy, "Halliburton#01")]
        [SemanticFact("BaseStarMeasuredRawWeight#01", Verbs.Enum.IsProvidedBy, "Halliburton#01")]
        [OPCUANode("http://ddhub.no/BaseStarDataManifest/Variables/", "BaseStarDataManifest.", "AverageRawWeight")]
        public ScalarProperty? AverageRawWeight { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("BaseStarMeasuredMinRawWeight")]
        [SemanticFact("BaseStarMeasuredMinRawWeight", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaseStarMeasuredMinRawWeight#01", Nouns.Enum.DerivedMeasurement)]
        [SemanticFact("BaseStarMeasuredMinRawWeight#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaseStarMeasuredMinRawWeight#01", Verbs.Enum.HasDynamicValue, "BaseStarMeasuredMinRawWeight")]
        [SemanticFact("BaseStarMeasuredMinRawWeight#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.WeightOnBitDrilling)]
        [SemanticFact("MovingMinBaseStarMeasuredMinRawWeight", Nouns.Enum.MovingMin)]
        [SemanticFact("BaseStarMeasuredMinRawWeight#01", Verbs.Enum.IsTransformationOutput, "MovingMinBaseStarMeasuredMinRawWeight")]
        [SemanticFact("BaseStarMeasuredRawWeight", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaseStarMeasuredRawWeight#01", Nouns.Enum.DerivedMeasurement)]
        [SemanticFact("BaseStarMeasuredRawWeight#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaseStarMeasuredRawWeight#01", Verbs.Enum.HasDynamicValue, "BaseStarMeasuredRawWeight")]
        [SemanticFact("BaseStarMeasuredRawWeight#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.WeightOnBitDrilling)]
        [SemanticFact("BaseStarMeasuredRawWeight#01", Verbs.Enum.IsTransformationInput, "MovingMinBaseStarMeasuredMinRawWeight")]
        [SemanticFact("GaussianUncertaintyBaseStarMeasuredMinRawWeight#01", Nouns.Enum.GaussianUncertainty)]
        [SemanticFact("BaseStarMeasuredMinRawWeight#01", Verbs.Enum.HasUncertainty, "GaussianUncertaintyBaseStarMeasuredMinRawWeight#01")]
        [SemanticFact("GaussianUncertaintyBaseStarMeasuredMinRawWeight#01", Verbs.Enum.HasUncertaintyMean, "BaseStarMeasuredMinRawWeight#01")]
        [SemanticFact("mudPulseTelemetry", Nouns.Enum.MudPulseTelemetry)]
        [SemanticFact("BaseStarMeasuredMinRawWeight#01", Verbs.Enum.IsTransmittedBy, "mudPulseTelemetry")]
        [SemanticFact("BHA#01", Nouns.Enum.BHAMechanicalLogicalElement)]
        [SemanticFact("BaseStarMeasuredMinRawWeight#01", Verbs.Enum.IsMechanicallyLocatedAt, "BHA#01")]
        [SemanticFact("BaseStarMeasuredRawWeight#01", Verbs.Enum.IsMechanicallyLocatedAt, "BHA#01")]
        [SemanticFact("Halliburton#01", Nouns.Enum.InstrumentationCompany)]
        [SemanticFact("BaseStarMeasuredMinRawWeight#01", Verbs.Enum.IsProvidedBy, "Halliburton#01")]
        [SemanticFact("BaseStarMeasuredRawWeight#01", Verbs.Enum.IsProvidedBy, "Halliburton#01")]
        [OPCUANode("http://ddhub.no/BaseStarDataManifest/Variables/", "BaseStarDataManifest.", "MinRawWeight")]
        public ScalarProperty? MinRawWeight { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("BaseStarMeasuredMaxRawWeight")]
        [SemanticFact("BaseStarMeasuredMaxRawWeight", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaseStarMeasuredMaxRawWeight#01", Nouns.Enum.DerivedMeasurement)]
        [SemanticFact("BaseStarMeasuredMaxRawWeight#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaseStarMeasuredMaxRawWeight#01", Verbs.Enum.HasDynamicValue, "BaseStarMeasuredMaxRawWeight")]
        [SemanticFact("BaseStarMeasuredMaxRawWeight#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.WeightOnBitDrilling)]
        [SemanticFact("MovingMaxBaseStarMeasuredMaxRawWeight", Nouns.Enum.MovingMax)]
        [SemanticFact("BaseStarMeasuredMaxRawWeight#01", Verbs.Enum.IsTransformationOutput, "MovingMaxBaseStarMeasuredMaxRawWeight")]
        [SemanticFact("BaseStarMeasuredRawWeight", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaseStarMeasuredRawWeight#01", Nouns.Enum.DerivedMeasurement)]
        [SemanticFact("BaseStarMeasuredRawWeight#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaseStarMeasuredRawWeight#01", Verbs.Enum.HasDynamicValue, "BaseStarMeasuredRawWeight")]
        [SemanticFact("BaseStarMeasuredRawWeight#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.WeightOnBitDrilling)]
        [SemanticFact("BaseStarMeasuredRawWeight#01", Verbs.Enum.IsTransformationInput, "MovingMaxBaseStarMeasuredMaxRawWeight")]
        [SemanticFact("GaussianUncertaintyBaseStarMeasuredMaxRawWeight#01", Nouns.Enum.GaussianUncertainty)]
        [SemanticFact("BaseStarMeasuredMaxRawWeight#01", Verbs.Enum.HasUncertainty, "GaussianUncertaintyBaseStarMeasuredMaxRawWeight#01")]
        [SemanticFact("GaussianUncertaintyBaseStarMeasuredMaxRawWeight#01", Verbs.Enum.HasUncertaintyMean, "BaseStarMeasuredMaxRawWeight#01")]
        [SemanticFact("mudPulseTelemetry", Nouns.Enum.MudPulseTelemetry)]
        [SemanticFact("BaseStarMeasuredMaxRawWeight#01", Verbs.Enum.IsTransmittedBy, "mudPulseTelemetry")]
        [SemanticFact("BHA#01", Nouns.Enum.BHAMechanicalLogicalElement)]
        [SemanticFact("BaseStarMeasuredMaxRawWeight#01", Verbs.Enum.IsMechanicallyLocatedAt, "BHA#01")]
        [SemanticFact("BaseStarMeasuredRawWeight#01", Verbs.Enum.IsMechanicallyLocatedAt, "BHA#01")]
        [SemanticFact("Halliburton#01", Nouns.Enum.InstrumentationCompany)]
        [SemanticFact("BaseStarMeasuredMaxRawWeight#01", Verbs.Enum.IsProvidedBy, "Halliburton#01")]
        [SemanticFact("BaseStarMeasuredRawWeight#01", Verbs.Enum.IsProvidedBy, "Halliburton#01")]
        [OPCUANode("http://ddhub.no/BaseStarDataManifest/Variables/", "BaseStarDataManifest.", "MaxRawWeight")]
        public GaussianDrillingProperty? MaxRawWeight { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("TareBitWeightForMudPulseTelemetry")]
        [SemanticFact("TareBitWeightForMudPulseTelemetry", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("TareBitWeightForMudPulseTelemetry#01", Nouns.Enum.ProcessData)]
        [SemanticFact("TareBitWeightForMudPulseTelemetry#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("TareBitWeightForMudPulseTelemetry#01", Verbs.Enum.HasDynamicValue, "TareBitWeightForMudPulseTelemetry")]
        [SemanticFact("TareBitWeightForMudPulseTelemetry#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.WeightOnBitDrilling)]
        [SemanticFact("mudPulseTelemetry", Nouns.Enum.MudPulseTelemetry)]
        [SemanticFact("TareBitWeightForMudPulseTelemetry#01", Verbs.Enum.IsTransmittedBy, "mudPulseTelemetry")]
        [SemanticFact("BHA#01", Nouns.Enum.BHAMechanicalLogicalElement)]
        [SemanticFact("TareBitWeightForMudPulseTelemetry#01", Verbs.Enum.IsMechanicallyLocatedAt, "BHA#01")]
        [SemanticFact("Halliburton#01", Nouns.Enum.InstrumentationCompany)]
        [SemanticFact("TareBitWeightForMudPulseTelemetry#01", Verbs.Enum.IsProvidedBy, "Halliburton#01")]
        [OPCUANode("http://ddhub.no/BaseStarDataManifest/Variables/", "BaseStarDataManifest.", "TareBitWeight")]
        public ScalarProperty? TareBitWeight { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("BaseStarMeasuredAverageBitWeight")]
        [SemanticFact("BaseStarMeasuredAverageBitWeight", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaseStarMeasuredAverageBitWeight#01", Nouns.Enum.DerivedMeasurement)]
        [SemanticFact("BaseStarMeasuredAverageBitWeight#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaseStarMeasuredAverageBitWeight#01", Verbs.Enum.HasDynamicValue, "BaseStarMeasuredAverageBitWeight")]
        [SemanticFact("BaseStarMeasuredAverageBitWeight#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.WeightOnBitDrilling)]
        [SemanticFact("MovingAverageBaseStarMeasuredAverageBitWeight", Nouns.Enum.MovingAverage)]
        [SemanticFact("BaseStarMeasuredAverageBitWeight#01", Verbs.Enum.IsTransformationOutput, "MovingAverageBaseStarMeasuredAverageBitWeight")]
        [SemanticFact("taringTransformationAverageWOB", Nouns.Enum.SummationTransformation)]
        [SemanticFact("BaseStarMeasuredAverageRawWeight", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaseStarMeasuredAverageRawWeight#01", Nouns.Enum.DerivedMeasurement)]
        [SemanticFact("BaseStarMeasuredAverageRawWeight#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaseStarMeasuredAverageRawWeight#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.WeightOnBitDrilling)]
        [SemanticFact("BaseStarMeasuredAverageRawWeight#01", Verbs.Enum.IsTransformationInput, "taringTransformationAverageWOB")]
        [SemanticFact("TareBitWeightForMudPulseTelemetry", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("TareBitWeightForMudPulseTelemetry#01", Nouns.Enum.ProcessData)]
        [SemanticFact("TareBitWeightForMudPulseTelemetry#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("TareBitWeightForMudPulseTelemetry#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.WeightOnBitDrilling)]
        [SemanticFact("TareBitWeightForMudPulseTelemetry#01", Verbs.Enum.IsTransformationInput, "taringTransformationAverageWOB")]
        [SemanticFact("BaseStarMeasuredAverageBitWeight#01", Verbs.Enum.IsTransformationOutput, "taringTransformationAverageWOB")]
        [SemanticFact("GaussianUncertaintyBaseStarMeasuredAverageBitWeight#01", Nouns.Enum.GaussianUncertainty)]
        [SemanticFact("BaseStarMeasuredAverageBitWeight#01", Verbs.Enum.HasUncertainty, "GaussianUncertaintyBaseStarMeasuredAverageBitWeight#01")]
        [SemanticFact("GaussianUncertaintyBaseStarMeasuredAverageBitWeight#01", Verbs.Enum.HasUncertaintyMean, "BaseStarMeasuredAverageBitWeight#01")]
        [SemanticFact("mudPulseTelemetry", Nouns.Enum.MudPulseTelemetry)]
        [SemanticFact("BaseStarMeasuredAverageBitWeight#01", Verbs.Enum.IsTransmittedBy, "mudPulseTelemetry")]
        [SemanticFact("Bit#01", Nouns.Enum.EndOfStringMechanicalLogicalElement)]
        [SemanticFact("BaseStarMeasuredAverageBitWeight#01", Verbs.Enum.IsMechanicallyLocatedAt, "Bit#01")]
        [SemanticFact("Halliburton#01", Nouns.Enum.InstrumentationCompany)]
        [SemanticFact("BaseStarMeasuredAverageBitWeight#01", Verbs.Enum.IsProvidedBy, "Halliburton#01")]
        [OPCUANode("http://ddhub.no/BaseStarDataManifest/Variables/", "BaseStarDataManifest.", "AverageBitWeight")]
        public ScalarProperty? AverageBitWeight { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("BaseStarMeasuredMinBitWeight")]
        [SemanticFact("BaseStarMeasuredMinBitWeight", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaseStarMeasuredMinBitWeight#01", Nouns.Enum.DerivedMeasurement)]
        [SemanticFact("BaseStarMeasuredMinBitWeight#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaseStarMeasuredMinBitWeight#01", Verbs.Enum.HasDynamicValue, "BaseStarMeasuredMinBitWeight")]
        [SemanticFact("BaseStarMeasuredMinBitWeight#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.WeightOnBitDrilling)]
        [SemanticFact("MovingMinBaseStarMeasuredMinBitWeight", Nouns.Enum.MovingMin)]
        [SemanticFact("BaseStarMeasuredMinBitWeight#01", Verbs.Enum.IsTransformationOutput, "MovingMinBaseStarMeasuredMinBitWeight")]
        [SemanticFact("taringTransformationMinWOB", Nouns.Enum.SummationTransformation)]
        [SemanticFact("BaseStarMeasuredMinRawWeight", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaseStarMeasuredMinRawWeight#01", Nouns.Enum.DerivedMeasurement)]
        [SemanticFact("BaseStarMeasuredMinRawWeight#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaseStarMeasuredMinRawWeight#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.WeightOnBitDrilling)]
        [SemanticFact("BaseStarMeasuredMinRawWeight#01", Verbs.Enum.IsTransformationInput, "taringTransformationMinWOB")]
        [SemanticFact("TareBitWeightForMudPulseTelemetry", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("TareBitWeightForMudPulseTelemetry#01", Nouns.Enum.ProcessData)]
        [SemanticFact("TareBitWeightForMudPulseTelemetry#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("TareBitWeightForMudPulseTelemetry#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.WeightOnBitDrilling)]
        [SemanticFact("TareBitWeightForMudPulseTelemetry#01", Verbs.Enum.IsTransformationInput, "taringTransformationMinWOB")]
        [SemanticFact("BaseStarMeasuredMinBitWeight#01", Verbs.Enum.IsTransformationOutput, "taringTransformationMinWOB")]
        [SemanticFact("GaussianUncertaintyBaseStarMeasuredMinBitWeight#01", Nouns.Enum.GaussianUncertainty)]
        [SemanticFact("BaseStarMeasuredMinBitWeight#01", Verbs.Enum.HasUncertainty, "GaussianUncertaintyBaseStarMeasuredMinBitWeight#01")]
        [SemanticFact("GaussianUncertaintyBaseStarMeasuredMinBitWeight#01", Verbs.Enum.HasUncertaintyMean, "BaseStarMeasuredMinBitWeight#01")]
        [SemanticFact("mudPulseTelemetry", Nouns.Enum.MudPulseTelemetry)]
        [SemanticFact("BaseStarMeasuredMinBitWeight#01", Verbs.Enum.IsTransmittedBy, "mudPulseTelemetry")]
        [SemanticFact("Bit#01", Nouns.Enum.EndOfStringMechanicalLogicalElement)]
        [SemanticFact("BaseStarMeasuredMinBitWeight#01", Verbs.Enum.IsMechanicallyLocatedAt, "Bit#01")]
        [SemanticFact("Halliburton#01", Nouns.Enum.InstrumentationCompany)]
        [SemanticFact("BaseStarMeasuredMinBitWeight#01", Verbs.Enum.IsProvidedBy, "Halliburton#01")]
        [OPCUANode("http://ddhub.no/BaseStarDataManifest/Variables/", "BaseStarDataManifest.", "MinBitWeight")]
        public ScalarProperty? MinBitWeight { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("BaseStarMeasuredMaxBitWeight")]
        [SemanticFact("BaseStarMeasuredMaxBitWeight", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaseStarMeasuredMaxBitWeight#01", Nouns.Enum.DerivedMeasurement)]
        [SemanticFact("BaseStarMeasuredMaxBitWeight#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaseStarMeasuredMaxBitWeight#01", Verbs.Enum.HasDynamicValue, "BaseStarMeasuredMaxBitWeight")]
        [SemanticFact("BaseStarMeasuredMaxBitWeight#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.WeightOnBitDrilling)]
        [SemanticFact("MovingMaxBaseStarMeasuredMaxBitWeight", Nouns.Enum.MovingMax)]
        [SemanticFact("BaseStarMeasuredMaxBitWeight#01", Verbs.Enum.IsTransformationOutput, "MovingMaxBaseStarMeasuredMaxBitWeight")]
        [SemanticFact("taringTransformationMaxWOB", Nouns.Enum.SummationTransformation)]
        [SemanticFact("BaseStarMeasuredMaxRawWeight", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaseStarMeasuredMaxRawWeight#01", Nouns.Enum.DerivedMeasurement)]
        [SemanticFact("BaseStarMeasuredMaxRawWeight#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaseStarMeasuredMaxRawWeight#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.WeightOnBitDrilling)]
        [SemanticFact("BaseStarMeasuredMaxRawWeight#01", Verbs.Enum.IsTransformationInput, "taringTransformationMaxWOB")]
        [SemanticFact("TareBitWeightForMudPulseTelemetry", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("TareBitWeightForMudPulseTelemetry#01", Nouns.Enum.ProcessData)]
        [SemanticFact("TareBitWeightForMudPulseTelemetry#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("TareBitWeightForMudPulseTelemetry#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.WeightOnBitDrilling)]
        [SemanticFact("TareBitWeightForMudPulseTelemetry#01", Verbs.Enum.IsTransformationInput, "taringTransformationMaxWOB")]
        [SemanticFact("BaseStarMeasuredMaxBitWeight#01", Verbs.Enum.IsTransformationOutput, "taringTransformationMaxWOB")]
        [SemanticFact("GaussianUncertaintyBaseStarMeasuredMaxBitWeight#01", Nouns.Enum.GaussianUncertainty)]
        [SemanticFact("BaseStarMeasuredMaxBitWeight#01", Verbs.Enum.HasUncertainty, "GaussianUncertaintyBaseStarMeasuredMaxBitWeight#01")]
        [SemanticFact("GaussianUncertaintyBaseStarMeasuredMaxBitWeight#01", Verbs.Enum.HasUncertaintyMean, "BaseStarMeasuredMaxBitWeight#01")]
        [SemanticFact("mudPulseTelemetry", Nouns.Enum.MudPulseTelemetry)]
        [SemanticFact("BaseStarMeasuredMaxBitWeight#01", Verbs.Enum.IsTransmittedBy, "mudPulseTelemetry")]
        [SemanticFact("Bit#01", Nouns.Enum.EndOfStringMechanicalLogicalElement)]
        [SemanticFact("BaseStarMeasuredMaxBitWeight#01", Verbs.Enum.IsMechanicallyLocatedAt, "Bit#01")]
        [SemanticFact("Halliburton#01", Nouns.Enum.InstrumentationCompany)]
        [SemanticFact("BaseStarMeasuredMaxBitWeight#01", Verbs.Enum.IsProvidedBy, "Halliburton#01")]
        [OPCUANode("http://ddhub.no/BaseStarDataManifest/Variables/", "BaseStarDataManifest.", "MaxBitWeight")]
        public ScalarProperty? MaxBitWeight { get; set; } = null;

        // ------------------------
        // RAW TORQUE + BIAS + CORRECTED + BIT TORQUE
        // ------------------------

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("BaseStarMeasuredAverageRawTorque")]
        [SemanticFact("BaseStarMeasuredAverageRawTorque", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaseStarMeasuredAverageRawTorque#01", Nouns.Enum.DerivedMeasurement)]
        [SemanticFact("BaseStarMeasuredAverageRawTorque#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaseStarMeasuredAverageRawTorque#01", Verbs.Enum.HasDynamicValue, "BaseStarMeasuredAverageRawTorque")]
        [SemanticFact("BaseStarMeasuredAverageRawTorque#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.TorqueDrilling)]
        [SemanticFact("MovingAverageBaseStarMeasuredAverageRawTorque", Nouns.Enum.MovingAverage)]
        [SemanticFact("BaseStarMeasuredAverageRawTorque#01", Verbs.Enum.IsTransformationOutput, "MovingAverageBaseStarMeasuredAverageRawTorque")]
        [SemanticFact("BaseStarMeasuredRawTorque", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaseStarMeasuredRawTorque#01", Nouns.Enum.DerivedMeasurement)]
        [SemanticFact("BaseStarMeasuredRawTorque#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaseStarMeasuredRawTorque#01", Verbs.Enum.HasDynamicValue, "BaseStarMeasuredRawTorque")]
        [SemanticFact("BaseStarMeasuredRawTorque#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.TorqueDrilling)]
        [SemanticFact("BaseStarMeasuredRawTorque#01", Verbs.Enum.IsTransformationInput, "MovingAverageBaseStarMeasuredAverageRawTorque")]
        [SemanticFact("GaussianUncertaintyBaseStarMeasuredAverageRawTorque#01", Nouns.Enum.GaussianUncertainty)]
        [SemanticFact("BaseStarMeasuredAverageRawTorque#01", Verbs.Enum.HasUncertainty, "GaussianUncertaintyBaseStarMeasuredAverageRawTorque#01")]
        [SemanticFact("GaussianUncertaintyBaseStarMeasuredAverageRawTorque#01", Verbs.Enum.HasUncertaintyMean, "BaseStarMeasuredAverageRawTorque#01")]
        [SemanticFact("mudPulseTelemetry", Nouns.Enum.MudPulseTelemetry)]
        [SemanticFact("BaseStarMeasuredAverageRawTorque#01", Verbs.Enum.IsTransmittedBy, "mudPulseTelemetry")]
        [SemanticFact("BHA#01", Nouns.Enum.BHAMechanicalLogicalElement)]
        [SemanticFact("BaseStarMeasuredAverageRawTorque#01", Verbs.Enum.IsMechanicallyLocatedAt, "BHA#01")]
        [SemanticFact("BaseStarMeasuredRawTorque#01", Verbs.Enum.IsMechanicallyLocatedAt, "BHA#01")]
        [SemanticFact("Halliburton#01", Nouns.Enum.InstrumentationCompany)]
        [SemanticFact("BaseStarMeasuredAverageRawTorque#01", Verbs.Enum.IsProvidedBy, "Halliburton#01")]
        [SemanticFact("BaseStarMeasuredRawTorque#01", Verbs.Enum.IsProvidedBy, "Halliburton#01")]
        [OPCUANode("http://ddhub.no/BaseStarDataManifest/Variables/", "BaseStarDataManifest.", "AverageRawTorque")]
        public ScalarProperty? AverageRawTorque { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("BaseStarMeasuredMinRawTorque")]
        [SemanticFact("BaseStarMeasuredMinRawTorque", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaseStarMeasuredMinRawTorque#01", Nouns.Enum.DerivedMeasurement)]
        [SemanticFact("BaseStarMeasuredMinRawTorque#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaseStarMeasuredMinRawTorque#01", Verbs.Enum.HasDynamicValue, "BaseStarMeasuredMinRawTorque")]
        [SemanticFact("BaseStarMeasuredMinRawTorque#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.TorqueDrilling)]
        [SemanticFact("MovingMinBaseStarMeasuredMinRawTorque", Nouns.Enum.MovingMin)]
        [SemanticFact("BaseStarMeasuredMinRawTorque#01", Verbs.Enum.IsTransformationOutput, "MovingMinBaseStarMeasuredMinRawTorque")]
        [SemanticFact("BaseStarMeasuredRawTorque", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaseStarMeasuredRawTorque#01", Nouns.Enum.DerivedMeasurement)]
        [SemanticFact("BaseStarMeasuredRawTorque#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaseStarMeasuredRawTorque#01", Verbs.Enum.HasDynamicValue, "BaseStarMeasuredRawTorque")]
        [SemanticFact("BaseStarMeasuredRawTorque#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.TorqueDrilling)]
        [SemanticFact("BaseStarMeasuredRawTorque#01", Verbs.Enum.IsTransformationInput, "MovingMinBaseStarMeasuredMinRawTorque")]
        [SemanticFact("GaussianUncertaintyBaseStarMeasuredMinRawTorque#01", Nouns.Enum.GaussianUncertainty)]
        [SemanticFact("BaseStarMeasuredMinRawTorque#01", Verbs.Enum.HasUncertainty, "GaussianUncertaintyBaseStarMeasuredMinRawTorque#01")]
        [SemanticFact("GaussianUncertaintyBaseStarMeasuredMinRawTorque#01", Verbs.Enum.HasUncertaintyMean, "BaseStarMeasuredMinRawTorque#01")]
        [SemanticFact("mudPulseTelemetry", Nouns.Enum.MudPulseTelemetry)]
        [SemanticFact("BaseStarMeasuredMinRawTorque#01", Verbs.Enum.IsTransmittedBy, "mudPulseTelemetry")]
        [SemanticFact("BHA#01", Nouns.Enum.BHAMechanicalLogicalElement)]
        [SemanticFact("BaseStarMeasuredMinRawTorque#01", Verbs.Enum.IsMechanicallyLocatedAt, "BHA#01")]
        [SemanticFact("BaseStarMeasuredRawTorque#01", Verbs.Enum.IsMechanicallyLocatedAt, "BHA#01")]
        [SemanticFact("Halliburton#01", Nouns.Enum.InstrumentationCompany)]
        [SemanticFact("BaseStarMeasuredMinRawTorque#01", Verbs.Enum.IsProvidedBy, "Halliburton#01")]
        [SemanticFact("BaseStarMeasuredRawTorque#01", Verbs.Enum.IsProvidedBy, "Halliburton#01")]
        [OPCUANode("http://ddhub.no/BaseStarDataManifest/Variables/", "BaseStarDataManifest.", "MinRawTorque")]
        public ScalarProperty? MinRawTorque { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("BaseStarMeasuredMaxRawTorque")]
        [SemanticFact("BaseStarMeasuredMaxRawTorque", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaseStarMeasuredMaxRawTorque#01", Nouns.Enum.DerivedMeasurement)]
        [SemanticFact("BaseStarMeasuredMaxRawTorque#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaseStarMeasuredMaxRawTorque#01", Verbs.Enum.HasDynamicValue, "BaseStarMeasuredMaxRawTorque")]
        [SemanticFact("BaseStarMeasuredMaxRawTorque#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.TorqueDrilling)]
        [SemanticFact("MovingMaxBaseStarMeasuredMaxRawTorque", Nouns.Enum.MovingMax)]
        [SemanticFact("BaseStarMeasuredMaxRawTorque#01", Verbs.Enum.IsTransformationOutput, "MovingMaxBaseStarMeasuredMaxRawTorque")]
        [SemanticFact("BaseStarMeasuredRawTorque", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaseStarMeasuredRawTorque#01", Nouns.Enum.DerivedMeasurement)]
        [SemanticFact("BaseStarMeasuredRawTorque#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaseStarMeasuredRawTorque#01", Verbs.Enum.HasDynamicValue, "BaseStarMeasuredRawTorque")]
        [SemanticFact("BaseStarMeasuredRawTorque#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.TorqueDrilling)]
        [SemanticFact("BaseStarMeasuredRawTorque#01", Verbs.Enum.IsTransformationInput, "MovingMaxBaseStarMeasuredMaxRawTorque")]
        [SemanticFact("GaussianUncertaintyBaseStarMeasuredMaxRawTorque#01", Nouns.Enum.GaussianUncertainty)]
        [SemanticFact("BaseStarMeasuredMaxRawTorque#01", Verbs.Enum.HasUncertainty, "GaussianUncertaintyBaseStarMeasuredMaxRawTorque#01")]
        [SemanticFact("GaussianUncertaintyBaseStarMeasuredMaxRawTorque#01", Verbs.Enum.HasUncertaintyMean, "BaseStarMeasuredMaxRawTorque#01")]
        [SemanticFact("mudPulseTelemetry", Nouns.Enum.MudPulseTelemetry)]
        [SemanticFact("BaseStarMeasuredMaxRawTorque#01", Verbs.Enum.IsTransmittedBy, "mudPulseTelemetry")]
        [SemanticFact("BHA#01", Nouns.Enum.BHAMechanicalLogicalElement)]
        [SemanticFact("BaseStarMeasuredMaxRawTorque#01", Verbs.Enum.IsMechanicallyLocatedAt, "BHA#01")]
        [SemanticFact("BaseStarMeasuredRawTorque#01", Verbs.Enum.IsMechanicallyLocatedAt, "BHA#01")]
        [SemanticFact("Halliburton#01", Nouns.Enum.InstrumentationCompany)]
        [SemanticFact("BaseStarMeasuredMaxRawTorque#01", Verbs.Enum.IsProvidedBy, "Halliburton#01")]
        [SemanticFact("BaseStarMeasuredRawTorque#01", Verbs.Enum.IsProvidedBy, "Halliburton#01")]
        [OPCUANode("http://ddhub.no/BaseStarDataManifest/Variables/", "BaseStarDataManifest.", "MaxRawTorque")]
        public ScalarProperty? MaxRawTorque { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("TorqueBiasForMudPulseTelemetry")]
        [SemanticFact("TorqueBiasForMudPulseTelemetry", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("TorqueBiasForMudPulseTelemetry#01", Nouns.Enum.ProcessData)]
        [SemanticFact("TorqueBiasForMudPulseTelemetry#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("TorqueBiasForMudPulseTelemetry#01", Verbs.Enum.HasDynamicValue, "TorqueBiasForMudPulseTelemetry")]
        [SemanticFact("TorqueBiasForMudPulseTelemetry#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.TorqueDrilling)]
        [SemanticFact("mudPulseTelemetry", Nouns.Enum.MudPulseTelemetry)]
        [SemanticFact("TorqueBiasForMudPulseTelemetry#01", Verbs.Enum.IsTransmittedBy, "mudPulseTelemetry")]
        [SemanticFact("BHA#01", Nouns.Enum.BHAMechanicalLogicalElement)]
        [SemanticFact("TorqueBiasForMudPulseTelemetry#01", Verbs.Enum.IsMechanicallyLocatedAt, "BHA#01")]
        [SemanticFact("Halliburton#01", Nouns.Enum.InstrumentationCompany)]
        [SemanticFact("TorqueBiasForMudPulseTelemetry#01", Verbs.Enum.IsProvidedBy, "Halliburton#01")]
        [OPCUANode("http://ddhub.no/BaseStarDataManifest/Variables/", "BaseStarDataManifest.", "TorqueBias")]
        public ScalarProperty? TorqueBias { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("BaseStarMeasuredAverageCorrectedTorque")]
        [SemanticFact("BaseStarMeasuredAverageCorrectedTorque", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaseStarMeasuredAverageCorrectedTorque#01", Nouns.Enum.CorrectedMeasurement)]
        [SemanticFact("BaseStarMeasuredAverageCorrectedTorque#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaseStarMeasuredAverageCorrectedTorque#01", Verbs.Enum.HasDynamicValue, "BaseStarMeasuredAverageCorrectedTorque")]
        [SemanticFact("BaseStarMeasuredAverageCorrectedTorque#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.TorqueDrilling)]
        [SemanticFact("MovingAverageBaseStarMeasuredAverageCorrectedTorque", Nouns.Enum.MovingAverage)]
        [SemanticFact("BaseStarMeasuredAverageCorrectedTorque#01", Verbs.Enum.IsTransformationOutput, "MovingAverageBaseStarMeasuredAverageCorrectedTorque")]
        [SemanticFact("taringTransformationAverageTorque", Nouns.Enum.SummationTransformation)]
        [SemanticFact("BaseStarMeasuredAverageRawTorque", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaseStarMeasuredAverageRawTorque#01", Nouns.Enum.DerivedMeasurement)]
        [SemanticFact("BaseStarMeasuredAverageRawTorque#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaseStarMeasuredAverageRawTorque#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.TorqueDrilling)]
        [SemanticFact("BaseStarMeasuredAverageRawTorque#01", Verbs.Enum.IsTransformationInput, "taringTransformationAverageTorque")]
        [SemanticFact("TorqueBiasForMudPulseTelemetry", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("TorqueBiasForMudPulseTelemetry#01", Nouns.Enum.ProcessData)]
        [SemanticFact("TorqueBiasForMudPulseTelemetry#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("TorqueBiasForMudPulseTelemetry#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.TorqueDrilling)]
        [SemanticFact("TorqueBiasForMudPulseTelemetry#01", Verbs.Enum.IsTransformationInput, "taringTransformationAverageTorque")]
        [SemanticFact("BaseStarMeasuredAverageCorrectedTorque#01", Verbs.Enum.IsTransformationOutput, "taringTransformationAverageTorque")]
        [SemanticFact("GaussianUncertaintyBaseStarMeasuredAverageCorrectedTorque#01", Nouns.Enum.GaussianUncertainty)]
        [SemanticFact("BaseStarMeasuredAverageCorrectedTorque#01", Verbs.Enum.HasUncertainty, "GaussianUncertaintyBaseStarMeasuredAverageCorrectedTorque#01")]
        [SemanticFact("GaussianUncertaintyBaseStarMeasuredAverageCorrectedTorque#01", Verbs.Enum.HasUncertaintyMean, "BaseStarMeasuredAverageCorrectedTorque#01")]
        [SemanticFact("mudPulseTelemetry", Nouns.Enum.MudPulseTelemetry)]
        [SemanticFact("BaseStarMeasuredAverageCorrectedTorque#01", Verbs.Enum.IsTransmittedBy, "mudPulseTelemetry")]
        [SemanticFact("BHA#01", Nouns.Enum.BHAMechanicalLogicalElement)]
        [SemanticFact("BaseStarMeasuredAverageCorrectedTorque#01", Verbs.Enum.IsMechanicallyLocatedAt, "BHA#01")]
        [SemanticFact("Halliburton#01", Nouns.Enum.InstrumentationCompany)]
        [SemanticFact("BaseStarMeasuredAverageCorrectedTorque#01", Verbs.Enum.IsProvidedBy, "Halliburton#01")]
        [OPCUANode("http://ddhub.no/BaseStarDataManifest/Variables/", "BaseStarDataManifest.", "AverageCorrectedTorque")]
        public ScalarProperty? AverageCorrectedTorque { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("BaseStarMeasuredMinCorrectedTorque")]
        [SemanticFact("BaseStarMeasuredMinCorrectedTorque", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaseStarMeasuredMinCorrectedTorque#01", Nouns.Enum.CorrectedMeasurement)]
        [SemanticFact("BaseStarMeasuredMinCorrectedTorque#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaseStarMeasuredMinCorrectedTorque#01", Verbs.Enum.HasDynamicValue, "BaseStarMeasuredMinCorrectedTorque")]
        [SemanticFact("BaseStarMeasuredMinCorrectedTorque#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.TorqueDrilling)]
        [SemanticFact("MovingMinBaseStarMeasuredMinCorrectedTorque", Nouns.Enum.MovingMin)]
        [SemanticFact("BaseStarMeasuredMinCorrectedTorque#01", Verbs.Enum.IsTransformationOutput, "MovingMinBaseStarMeasuredMinCorrectedTorque")]
        [SemanticFact("taringTransformationMinTorque", Nouns.Enum.SummationTransformation)]
        [SemanticFact("BaseStarMeasuredMinRawTorque", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaseStarMeasuredMinRawTorque#01", Nouns.Enum.DerivedMeasurement)]
        [SemanticFact("BaseStarMeasuredMinRawTorque#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaseStarMeasuredMinRawTorque#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.TorqueDrilling)]
        [SemanticFact("BaseStarMeasuredMinRawTorque#01", Verbs.Enum.IsTransformationInput, "taringTransformationMinTorque")]
        [SemanticFact("TorqueBiasForMudPulseTelemetry", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("TorqueBiasForMudPulseTelemetry#01", Nouns.Enum.ProcessData)]
        [SemanticFact("TorqueBiasForMudPulseTelemetry#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("TorqueBiasForMudPulseTelemetry#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.TorqueDrilling)]
        [SemanticFact("TorqueBiasForMudPulseTelemetry#01", Verbs.Enum.IsTransformationInput, "taringTransformationMinTorque")]
        [SemanticFact("BaseStarMeasuredMinCorrectedTorque#01", Verbs.Enum.IsTransformationOutput, "taringTransformationMinTorque")]
        [SemanticFact("GaussianUncertaintyBaseStarMeasuredMinCorrectedTorque#01", Nouns.Enum.GaussianUncertainty)]
        [SemanticFact("BaseStarMeasuredMinCorrectedTorque#01", Verbs.Enum.HasUncertainty, "GaussianUncertaintyBaseStarMeasuredMinCorrectedTorque#01")]
        [SemanticFact("GaussianUncertaintyBaseStarMeasuredMinCorrectedTorque#01", Verbs.Enum.HasUncertaintyMean, "BaseStarMeasuredMinCorrectedTorque#01")]
        [SemanticFact("mudPulseTelemetry", Nouns.Enum.MudPulseTelemetry)]
        [SemanticFact("BaseStarMeasuredMinCorrectedTorque#01", Verbs.Enum.IsTransmittedBy, "mudPulseTelemetry")]
        [SemanticFact("BHA#01", Nouns.Enum.BHAMechanicalLogicalElement)]
        [SemanticFact("BaseStarMeasuredMinCorrectedTorque#01", Verbs.Enum.IsMechanicallyLocatedAt, "BHA#01")]
        [SemanticFact("Halliburton#01", Nouns.Enum.InstrumentationCompany)]
        [SemanticFact("BaseStarMeasuredMinCorrectedTorque#01", Verbs.Enum.IsProvidedBy, "Halliburton#01")]
        [OPCUANode("http://ddhub.no/BaseStarDataManifest/Variables/", "BaseStarDataManifest.", "MinCorrectedTorque")]
        public ScalarProperty? MinCorrectedTorque { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("BaseStarMeasuredMaxCorrectedTorque")]
        [SemanticFact("BaseStarMeasuredMaxCorrectedTorque", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaseStarMeasuredMaxCorrectedTorque#01", Nouns.Enum.CorrectedMeasurement)]
        [SemanticFact("BaseStarMeasuredMaxCorrectedTorque#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaseStarMeasuredMaxCorrectedTorque#01", Verbs.Enum.HasDynamicValue, "BaseStarMeasuredMaxCorrectedTorque")]
        [SemanticFact("BaseStarMeasuredMaxCorrectedTorque#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.TorqueDrilling)]
        [SemanticFact("MovingMaxBaseStarMeasuredMaxCorrectedTorque", Nouns.Enum.MovingMax)]
        [SemanticFact("BaseStarMeasuredMaxCorrectedTorque#01", Verbs.Enum.IsTransformationOutput, "MovingMaxBaseStarMeasuredMaxCorrectedTorque")]
        [SemanticFact("taringTransformationMaxTorque", Nouns.Enum.SummationTransformation)]
        [SemanticFact("BaseStarMeasuredMaxRawTorque", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaseStarMeasuredMaxRawTorque#01", Nouns.Enum.DerivedMeasurement)]
        [SemanticFact("BaseStarMeasuredMaxRawTorque#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaseStarMeasuredMaxRawTorque#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.TorqueDrilling)]
        [SemanticFact("BaseStarMeasuredMaxRawTorque#01", Verbs.Enum.IsTransformationInput, "taringTransformationMaxTorque")]
        [SemanticFact("TorqueBiasForMudPulseTelemetry", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("TorqueBiasForMudPulseTelemetry#01", Nouns.Enum.ProcessData)]
        [SemanticFact("TorqueBiasForMudPulseTelemetry#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("TorqueBiasForMudPulseTelemetry#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.TorqueDrilling)]
        [SemanticFact("TorqueBiasForMudPulseTelemetry#01", Verbs.Enum.IsTransformationInput, "taringTransformationMaxTorque")]
        [SemanticFact("BaseStarMeasuredMaxCorrectedTorque#01", Verbs.Enum.IsTransformationOutput, "taringTransformationMaxTorque")]
        [SemanticFact("GaussianUncertaintyBaseStarMeasuredMaxCorrectedTorque#01", Nouns.Enum.GaussianUncertainty)]
        [SemanticFact("BaseStarMeasuredMaxCorrectedTorque#01", Verbs.Enum.HasUncertainty, "GaussianUncertaintyBaseStarMeasuredMaxCorrectedTorque#01")]
        [SemanticFact("GaussianUncertaintyBaseStarMeasuredMaxCorrectedTorque#01", Verbs.Enum.HasUncertaintyMean, "BaseStarMeasuredMaxCorrectedTorque#01")]
        [SemanticFact("mudPulseTelemetry", Nouns.Enum.MudPulseTelemetry)]
        [SemanticFact("BaseStarMeasuredMaxCorrectedTorque#01", Verbs.Enum.IsTransmittedBy, "mudPulseTelemetry")]
        [SemanticFact("BHA#01", Nouns.Enum.BHAMechanicalLogicalElement)]
        [SemanticFact("BaseStarMeasuredMaxCorrectedTorque#01", Verbs.Enum.IsMechanicallyLocatedAt, "BHA#01")]
        [SemanticFact("Halliburton#01", Nouns.Enum.InstrumentationCompany)]
        [SemanticFact("BaseStarMeasuredMaxCorrectedTorque#01", Verbs.Enum.IsProvidedBy, "Halliburton#01")]
        [OPCUANode("http://ddhub.no/BaseStarDataManifest/Variables/", "BaseStarDataManifest.", "MaxCorrectedTorque")]
        public ScalarProperty? MaxCorrectedTorque { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("BaseStarMeasuredAverageBitTorque")]
        [SemanticFact("BaseStarMeasuredAverageBitTorque", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaseStarMeasuredAverageBitTorque#01", Nouns.Enum.DerivedMeasurement)]
        [SemanticFact("BaseStarMeasuredAverageBitTorque#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaseStarMeasuredAverageBitTorque#01", Verbs.Enum.HasDynamicValue, "BaseStarMeasuredAverageBitTorque")]
        [SemanticFact("BaseStarMeasuredAverageBitTorque#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.TorqueDrilling)]
        [SemanticFact("MovingAverageBaseStarMeasuredAverageBitTorque", Nouns.Enum.MovingAverage)]
        [SemanticFact("BaseStarMeasuredAverageBitTorque#01", Verbs.Enum.IsTransformationOutput, "MovingAverageBaseStarMeasuredAverageBitTorque")]
        [SemanticFact("taringTransformationAverageBitTorque", Nouns.Enum.SummationTransformation)]
        [SemanticFact("BaseStarMeasuredAverageRawTorque", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaseStarMeasuredAverageRawTorque#01", Nouns.Enum.DerivedMeasurement)]
        [SemanticFact("BaseStarMeasuredAverageRawTorque#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaseStarMeasuredAverageRawTorque#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.TorqueDrilling)]
        [SemanticFact("BaseStarMeasuredAverageRawTorque#01", Verbs.Enum.IsTransformationInput, "taringTransformationAverageBitTorque")]
        [SemanticFact("TorqueBiasForMudPulseTelemetry", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("TorqueBiasForMudPulseTelemetry#01", Nouns.Enum.ProcessData)]
        [SemanticFact("TorqueBiasForMudPulseTelemetry#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("TorqueBiasForMudPulseTelemetry#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.TorqueDrilling)]
        [SemanticFact("TorqueBiasForMudPulseTelemetry#01", Verbs.Enum.IsTransformationInput, "taringTransformationAverageBitTorque")]
        [SemanticFact("BaseStarMeasuredAverageBitTorque#01", Verbs.Enum.IsTransformationOutput, "taringTransformationAverageBitTorque")]
        [SemanticFact("GaussianUncertaintyBaseStarMeasuredAverageBitTorque#01", Nouns.Enum.GaussianUncertainty)]
        [SemanticFact("BaseStarMeasuredAverageBitTorque#01", Verbs.Enum.HasUncertainty, "GaussianUncertaintyBaseStarMeasuredAverageBitTorque#01")]
        [SemanticFact("GaussianUncertaintyBaseStarMeasuredAverageBitTorque#01", Verbs.Enum.HasUncertaintyMean, "BaseStarMeasuredAverageBitTorque#01")]
        [SemanticFact("mudPulseTelemetry", Nouns.Enum.MudPulseTelemetry)]
        [SemanticFact("BaseStarMeasuredAverageBitTorque#01", Verbs.Enum.IsTransmittedBy, "mudPulseTelemetry")]
        [SemanticFact("Bit#01", Nouns.Enum.EndOfStringMechanicalLogicalElement)]
        [SemanticFact("BaseStarMeasuredAverageBitTorque#01", Verbs.Enum.IsMechanicallyLocatedAt, "Bit#01")]
        [SemanticFact("Halliburton#01", Nouns.Enum.InstrumentationCompany)]
        [SemanticFact("BaseStarMeasuredAverageBitTorque#01", Verbs.Enum.IsProvidedBy, "Halliburton#01")]
        [OPCUANode("http://ddhub.no/BaseStarDataManifest/Variables/", "BaseStarDataManifest.", "AverageBitTorque")]
        public ScalarProperty? AverageBitTorque { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("BaseStarMeasuredMinBitTorque")]
        [SemanticFact("BaseStarMeasuredMinBitTorque", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaseStarMeasuredMinBitTorque#01", Nouns.Enum.DerivedMeasurement)]
        [SemanticFact("BaseStarMeasuredMinBitTorque#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaseStarMeasuredMinBitTorque#01", Verbs.Enum.HasDynamicValue, "BaseStarMeasuredMinBitTorque")]
        [SemanticFact("BaseStarMeasuredMinBitTorque#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.TorqueDrilling)]
        [SemanticFact("MovingMinBaseStarMeasuredMinBitTorque", Nouns.Enum.MovingMin)]
        [SemanticFact("BaseStarMeasuredMinBitTorque#01", Verbs.Enum.IsTransformationOutput, "MovingMinBaseStarMeasuredMinBitTorque")]
        [SemanticFact("taringTransformationMinBitTorque", Nouns.Enum.SummationTransformation)]
        [SemanticFact("BaseStarMeasuredMinRawTorque", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaseStarMeasuredMinRawTorque#01", Nouns.Enum.DerivedMeasurement)]
        [SemanticFact("BaseStarMeasuredMinRawTorque#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaseStarMeasuredMinRawTorque#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.TorqueDrilling)]
        [SemanticFact("BaseStarMeasuredMinRawTorque#01", Verbs.Enum.IsTransformationInput, "taringTransformationMinBitTorque")]
        [SemanticFact("TorqueBiasForMudPulseTelemetry", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("TorqueBiasForMudPulseTelemetry#01", Nouns.Enum.ProcessData)]
        [SemanticFact("TorqueBiasForMudPulseTelemetry#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("TorqueBiasForMudPulseTelemetry#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.TorqueDrilling)]
        [SemanticFact("TorqueBiasForMudPulseTelemetry#01", Verbs.Enum.IsTransformationInput, "taringTransformationMinBitTorque")]
        [SemanticFact("BaseStarMeasuredMinBitTorque#01", Verbs.Enum.IsTransformationOutput, "taringTransformationMinBitTorque")]
        [SemanticFact("GaussianUncertaintyBaseStarMeasuredMinBitTorque#01", Nouns.Enum.GaussianUncertainty)]
        [SemanticFact("BaseStarMeasuredMinBitTorque#01", Verbs.Enum.HasUncertainty, "GaussianUncertaintyBaseStarMeasuredMinBitTorque#01")]
        [SemanticFact("GaussianUncertaintyBaseStarMeasuredMinBitTorque#01", Verbs.Enum.HasUncertaintyMean, "BaseStarMeasuredMinBitTorque#01")]
        [SemanticFact("mudPulseTelemetry", Nouns.Enum.MudPulseTelemetry)]
        [SemanticFact("BaseStarMeasuredMinBitTorque#01", Verbs.Enum.IsTransmittedBy, "mudPulseTelemetry")]
        [SemanticFact("Bit#01", Nouns.Enum.EndOfStringMechanicalLogicalElement)]
        [SemanticFact("BaseStarMeasuredMinBitTorque#01", Verbs.Enum.IsMechanicallyLocatedAt, "Bit#01")]
        [SemanticFact("Halliburton#01", Nouns.Enum.InstrumentationCompany)]
        [SemanticFact("BaseStarMeasuredMinBitTorque#01", Verbs.Enum.IsProvidedBy, "Halliburton#01")]
        [OPCUANode("http://ddhub.no/BaseStarDataManifest/Variables/", "BaseStarDataManifest.", "MinBitTorque")]
        public ScalarProperty? MinBitTorque { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("BaseStarMeasuredMaxBitTorque")]
        [SemanticFact("BaseStarMeasuredMaxBitTorque", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaseStarMeasuredMaxBitTorque#01", Nouns.Enum.DerivedMeasurement)]
        [SemanticFact("BaseStarMeasuredMaxBitTorque#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaseStarMeasuredMaxBitTorque#01", Verbs.Enum.HasDynamicValue, "BaseStarMeasuredMaxBitTorque")]
        [SemanticFact("BaseStarMeasuredMaxBitTorque#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.TorqueDrilling)]
        [SemanticFact("MovingMaxBaseStarMeasuredMaxBitTorque", Nouns.Enum.MovingMax)]
        [SemanticFact("BaseStarMeasuredMaxBitTorque#01", Verbs.Enum.IsTransformationOutput, "MovingMaxBaseStarMeasuredMaxBitTorque")]
        [SemanticFact("taringTransformationMaxBitTorque", Nouns.Enum.SummationTransformation)]
        [SemanticFact("BaseStarMeasuredAverageRawTorque", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaseStarMeasuredAverageRawTorque#01", Nouns.Enum.DerivedMeasurement)]
        [SemanticFact("BaseStarMeasuredAverageRawTorque#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaseStarMeasuredAverageRawTorque#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.TorqueDrilling)]
        [SemanticFact("BaseStarMeasuredAverageRawTorque#01", Verbs.Enum.IsTransformationInput, "taringTransformationMaxBitTorque")]
        [SemanticFact("TorqueBiasForMudPulseTelemetry", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("TorqueBiasForMudPulseTelemetry#01", Nouns.Enum.ProcessData)]
        [SemanticFact("TorqueBiasForMudPulseTelemetry#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("TorqueBiasForMudPulseTelemetry#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.TorqueDrilling)]
        [SemanticFact("TorqueBiasForMudPulseTelemetry#01", Verbs.Enum.IsTransformationInput, "taringTransformationMaxBitTorque")]
        [SemanticFact("BaseStarMeasuredMaxBitTorque#01", Verbs.Enum.IsTransformationOutput, "taringTransformationMaxBitTorque")]
        [SemanticFact("GaussianUncertaintyBaseStarMeasuredMaxBitTorque#01", Nouns.Enum.GaussianUncertainty)]
        [SemanticFact("BaseStarMeasuredMaxBitTorque#01", Verbs.Enum.HasUncertainty, "GaussianUncertaintyBaseStarMeasuredMaxBitTorque#01")]
        [SemanticFact("GaussianUncertaintyBaseStarMeasuredMaxBitTorque#01", Verbs.Enum.HasUncertaintyMean, "BaseStarMeasuredMaxBitTorque#01")]
        [SemanticFact("mudPulseTelemetry", Nouns.Enum.MudPulseTelemetry)]
        [SemanticFact("BaseStarMeasuredMaxBitTorque#01", Verbs.Enum.IsTransmittedBy, "mudPulseTelemetry")]
        [SemanticFact("Bit#01", Nouns.Enum.EndOfStringMechanicalLogicalElement)]
        [SemanticFact("BaseStarMeasuredMaxBitTorque#01", Verbs.Enum.IsMechanicallyLocatedAt, "Bit#01")]
        [SemanticFact("Halliburton#01", Nouns.Enum.InstrumentationCompany)]
        [SemanticFact("BaseStarMeasuredMaxBitTorque#01", Verbs.Enum.IsProvidedBy, "Halliburton#01")]
        [OPCUANode("http://ddhub.no/BaseStarDataManifest/Variables/", "BaseStarDataManifest.", "MaxBitTorque")]
        public ScalarProperty? MaxBitTorque { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("BaseStarMeasuredElectronicTemperature")]
        [SemanticFact("BaseStarMeasuredElectronicTemperature", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaseStarMeasuredElectronicTemperature#01", Nouns.Enum.DerivedMeasurement)]
        [SemanticFact("BaseStarMeasuredElectronicTemperature#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaseStarMeasuredElectronicTemperature#01", Verbs.Enum.HasDynamicValue, "BaseStarMeasuredElectronicTemperature")]
        [SemanticFact("BaseStarMeasuredElectronicTemperature#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.TemperatureDrilling)]
        [SemanticFact("MovingAverageBaseStarMeasuredElectronicTemperature", Nouns.Enum.MovingAverage)]
        [SemanticFact("BaseStarMeasuredElectronicTemperature#01", Verbs.Enum.IsTransformationOutput, "MovingAverageBaseStarMeasuredElectronicTemperature")]
        [SemanticFact("GaussianUncertaintyBaseStarMeasuredElectronicTemperature#01", Nouns.Enum.GaussianUncertainty)]
        [SemanticFact("BaseStarMeasuredElectronicTemperature#01", Verbs.Enum.HasUncertainty, "GaussianUncertaintyBaseStarMeasuredElectronicTemperature#01")]
        [SemanticFact("GaussianUncertaintyBaseStarMeasuredElectronicTemperature#01", Verbs.Enum.HasUncertaintyMean, "BaseStarMeasuredElectronicTemperature#01")]
        [SemanticFact("mudPulseTelemetry", Nouns.Enum.MudPulseTelemetry)]
        [SemanticFact("BaseStarMeasuredElectronicTemperature#01", Verbs.Enum.IsTransmittedBy, "mudPulseTelemetry")]
        [SemanticFact("topOfStringJunction#01", Nouns.Enum.TopOfStringJunction)]
        [SemanticFact("stringHydraulicBranch#01", Nouns.Enum.HydraulicBranch)]
        [SemanticFact("topOfStringJunction#01", Verbs.Enum.HasDownstreamBranch, "stringHydraulicBranch#01")]
        [SemanticFact("BaseStarMeasuredElectronicTemperature#01", Verbs.Enum.IsAssociatedToHydraulicBranch, "stringHydraulicBranch#01")]
        [SemanticFact("annulusOutletJunction#01", Nouns.Enum.AnnulusOutletJunction)]
        [SemanticFact("outletHydraulicBranch#01", Nouns.Enum.HydraulicBranch)]
        [SemanticFact("annulusOutletJunction#01", Verbs.Enum.HasUpstreamBranch, "outletHydraulicBranch#01")]
        [SemanticFact("BaseStarMeasuredElectronicTemperature#01", Verbs.Enum.IsAssociatedToHydraulicBranch, "outletHydraulicBranch#01")]
        [SemanticFact("BHA#01", Nouns.Enum.BHAMechanicalLogicalElement)]
        [SemanticFact("BaseStarMeasuredElectronicTemperature#01", Verbs.Enum.IsMechanicallyLocatedAt, "BHA#01")]
        [SemanticFact("Halliburton#01", Nouns.Enum.InstrumentationCompany)]
        [SemanticFact("BaseStarMeasuredElectronicTemperature#01", Verbs.Enum.IsProvidedBy, "Halliburton#01")]
        [OPCUANode("http://ddhub.no/BaseStarDataManifest/Variables/", "BaseStarDataManifest.", "ElectronicTemperature")]
        public ScalarProperty? ElectronicTemperature { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("BaseStarMeasuredStringPressure")]
        [SemanticFact("BaseStarMeasuredStringPressure", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaseStarMeasuredStringPressure#01", Nouns.Enum.DerivedMeasurement)]
        [SemanticFact("BaseStarMeasuredStringPressure#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaseStarMeasuredStringPressure#01", Verbs.Enum.HasDynamicValue, "BaseStarMeasuredStringPressure")]
        [SemanticFact("BaseStarMeasuredStringPressure#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.PressureDrilling)]
        [SemanticFact("MovingAverageBaseStarMeasuredStringPressure", Nouns.Enum.MovingAverage)]
        [SemanticFact("BaseStarMeasuredStringPressure#01", Verbs.Enum.IsTransformationOutput, "MovingAverageBaseStarMeasuredStringPressure")]
        [SemanticFact("GaussianUncertaintyBaseStarMeasuredStringPressure#01", Nouns.Enum.GaussianUncertainty)]
        [SemanticFact("BaseStarMeasuredStringPressure#01", Verbs.Enum.HasUncertainty, "GaussianUncertaintyBaseStarMeasuredStringPressure#01")]
        [SemanticFact("GaussianUncertaintyBaseStarMeasuredStringPressure#01", Verbs.Enum.HasUncertaintyMean, "BaseStarMeasuredStringPressure#01")]
        [SemanticFact("mudPulseTelemetry", Nouns.Enum.MudPulseTelemetry)]
        [SemanticFact("BaseStarMeasuredStringPressure#01", Verbs.Enum.IsTransmittedBy, "mudPulseTelemetry")]
        [SemanticFact("topOfStringJunction#01", Nouns.Enum.TopOfStringJunction)]
        [SemanticFact("stringHydraulicBranch#01", Nouns.Enum.HydraulicBranch)]
        [SemanticFact("topOfStringJunction#01", Verbs.Enum.HasDownstreamBranch, "stringHydraulicBranch#01")]
        [SemanticFact("BaseStarMeasuredStringPressure#01", Verbs.Enum.IsAssociatedToHydraulicBranch, "stringHydraulicBranch#01")]
        [SemanticFact("BHA#01", Nouns.Enum.BHAMechanicalLogicalElement)]
        [SemanticFact("BaseStarMeasuredStringPressure#01", Verbs.Enum.IsMechanicallyLocatedAt, "BHA#01")]
        [SemanticFact("Halliburton#01", Nouns.Enum.InstrumentationCompany)]
        [SemanticFact("BaseStarMeasuredStringPressure#01", Verbs.Enum.IsProvidedBy, "Halliburton#01")]
        [OPCUANode("http://ddhub.no/BaseStarDataManifest/Variables/", "BaseStarDataManifest.", "StringPressure")]
        public ScalarProperty? StringPressure { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("BaseStarMeasuredAnnulusPressure")]
        [SemanticFact("BaseStarMeasuredAnnulusPressure", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaseStarMeasuredAnnulusPressure#01", Nouns.Enum.DerivedMeasurement)]
        [SemanticFact("BaseStarMeasuredAnnulusPressure#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaseStarMeasuredAnnulusPressure#01", Verbs.Enum.HasDynamicValue, "BaseStarMeasuredAnnulusPressure")]
        [SemanticFact("BaseStarMeasuredAnnulusPressure#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.PressureDrilling)]
        [SemanticFact("MovingAverageBaseStarMeasuredAnnulusPressure", Nouns.Enum.MovingAverage)]
        [SemanticFact("BaseStarMeasuredAnnulusPressure#01", Verbs.Enum.IsTransformationOutput, "MovingAverageBaseStarMeasuredAnnulusPressure")]
        [SemanticFact("GaussianUncertaintyBaseStarMeasuredAnnulusPressure#01", Nouns.Enum.GaussianUncertainty)]
        [SemanticFact("BaseStarMeasuredAnnulusPressure#01", Verbs.Enum.HasUncertainty, "GaussianUncertaintyBaseStarMeasuredAnnulusPressure#01")]
        [SemanticFact("GaussianUncertaintyBaseStarMeasuredAnnulusPressure#01", Verbs.Enum.HasUncertaintyMean, "BaseStarMeasuredAnnulusPressure#01")]
        [SemanticFact("mudPulseTelemetry", Nouns.Enum.MudPulseTelemetry)]
        [SemanticFact("BaseStarMeasuredAnnulusPressure#01", Verbs.Enum.IsTransmittedBy, "mudPulseTelemetry")]
        [SemanticFact("annulusOutletJunction#01", Nouns.Enum.AnnulusOutletJunction)]
        [SemanticFact("outletHydraulicBranch#01", Nouns.Enum.HydraulicBranch)]
        [SemanticFact("annulusOutletJunction#01", Verbs.Enum.HasUpstreamBranch, "outletHydraulicBranch#01")]
        [SemanticFact("BaseStarMeasuredAnnulusPressure#01", Verbs.Enum.IsAssociatedToHydraulicBranch, "outletHydraulicBranch#01")]
        [SemanticFact("BHA#01", Nouns.Enum.BHAMechanicalLogicalElement)]
        [SemanticFact("BaseStarMeasuredAnnulusPressure#01", Verbs.Enum.IsMechanicallyLocatedAt, "BHA#01")]
        [SemanticFact("Halliburton#01", Nouns.Enum.InstrumentationCompany)]
        [SemanticFact("BaseStarMeasuredAnnulusPressure#01", Verbs.Enum.IsProvidedBy, "Halliburton#01")]
        [OPCUANode("http://ddhub.no/BaseStarDataManifest/Variables/", "BaseStarDataManifest.", "AnnulusPressure")]
        public ScalarProperty? AnnulusPressure { get; set; } = null;

    }
}
